var GAME_LEVELS = [
  ["                                                                     !!!        ",
   "                                                                    !x!x!       ",
   "                                                                   !x!!!x!      ",
   "                                               xxxxxxxx            !x!!!x!      ",
   " @                                                                !!x!!!x!      ",
   "xxxxx        xxx!!!!!!!!!xxx       xxxxxxxxxx!!!!!!!!!!!xxxx     !xx!!!!!x!     ",
   "!!!!!x          x!!!!!!!x         x          x!!!!!!!!!xxxxx    !x!!!!!!!!x!    ",
   "!!!!!!x          xxxvxxx         x            x!!!!!!!xxxxxx    vx!!!!!!!!x!    ",
   "!!!!!!!xxx                    xxx              x!!!!!!xxxxxx     x!!!!!!!!!x!   ",
   "!!!!!!!!!!x                  x                 xvxx!!!xxxxxx     x!!!!!!!!!!x!  ",
   "!!!!!!!!!!!x     x      x   x        xxxxx         xvxxxxxx      x!!!!!!!!!!!x! ",
   "!!!!!!!!!!!!xxxxxxxxxxxxxxxx                         xxxxx       x!!!!!!!!!!!x! ",
   "!!!!!!!!!!!x                                                     x!!!!!!!!!!!x! ",
   "!!!!xxxxxxx                                                      x!!!!!!!!!!!x! ",
   "!!!v             xxxxxxxxxxxxxxxxx!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!x! ",
   "xxx          xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x! ",
   "             x!!!!xxxxxvxxxxxxxxxx!!!!xxxxxxvxxxvxxxxxxxxxx!!!!!!!xxxx!!!!!!!xv ",
   "           xxxvxxxx              x!!!!x                   x!!!!!!x   xxxxvxxxx  ",
   "          x                       xxxx                     xxxxxx               ",
   "                                                                                ",
   "                                                                                ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                                                              xo",
   "                                                                              xx"],
  ["                                                                                                                  ",
   "                                                                xxxxxxxxxxx                                       ",
   "          xxxxxxxxxxxxxxxxxxxxxxxxxxx                         xx           x    xxx                           x!x ",
   "          x                          xx                     xx              x x!!!x                         x!!x  ",
   "          x                            x                   x                 xxxvxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!x  ",
   "          x          xxxxxxxxxxx       x          xxxxxxxxxx                                  x!!!!!!!!!!!!!!!!!x ",
   "          x          x!!!!!!!!!!x      x         x                                             x!!!!!!!!!!!!!!!!x ",
   "          xx         x!!!!!!!!!!x       xxxxxxxxx                  x   x    x                   =xxxvxxxxxvxxxxx  ",
   "          x         xx!!!!!!!!!!!xx                    xxxxxxxx  |   |   |  xxxxxxxxxxxxx                         ",
   "          x          x!!!!!!!!!!!!!x                  x       xx!!!!!!!!!!!xx            xx                       ",
   "          x    x     x!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxx        xxxx!!!!!xxxx               xx                     ",
   "          x          x!!!!!!!!!!!!!x                              xxxvxxx                   xxxxxxxxxxxxxxxxxxxxxx",
   "          x          x!!!!!!!!!!!!!x                                                         x                  o ",
   "          x          x!!!!!!!!!!!!x                                                          x                    ",
   "          x         xx!!!!!!!xxxxx      x                                                    x                 xx ",
   "          x          x!!!!!!x          x x                                                   x             xxx    ",
   "          x          xxxvxxx          x   x                       xxxxxx         x           x                    ",
   "          xxxxx                       x   x                      x      x                    x                    ",
   "          x                          x     xxxxx     x     xxxxxx        xxxx!!!!!!!!!x      x       xxxxx        ",
   "          x!!!!!!!!!x                x         x!!!!!x!!!!!x                x!!!!!!!!!x      x       x!!!!!!!!!!!!",
   "          x!!!!!!!!!x              @ x         x!!!!!x!!!!!x                x!!!!!!!!!x            xxx!!!!!!!!!!!!",
   "          xxxxxxxxxxxxxxxxxxxxxxxxxxxx         x!!!!!x!!!!!x                x!!!!!!!!!x              x!!!!!!!!!!!!",
   "                                               x!!!!!x!!!!!x                x!!!!!!!!!x              x!!!!!!!!!!!!",
   "                                               xxxxxxxxxxxxx                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  "],
  ["                                                                                        ",
   "                                                                                        ",
   "    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    ",
   "    x!!!!!!!!!!!!!!!!!!!!!!!!!!!x                               x         |!!!!!!!!x    ",
   "    x!!!!!xxxxxxxxxxxvxxxxxxxvxxx                               x          x!!!!!!!x    ",
   "    x!!xxx                                                      x          xxxxvxxxx    ",
   "    xxv                                      @                  x                  x    ",
   "    x                                 xxxxxxxxxxxxx       xxxxxxx                  x    ",
   "    x                                 x       |   x                   x            x    ",
   "    x          xxxxxxxxxxxxxxxxxxxxxxxx           xx                  x            x    ",
   "    x          x!!!!!!!!!!!!!|                    x                   x            x    ",
   "    x       xxxxxxxvxxxxxxxxx                     xxxxxxxxxxxxxxxxxxxxxxxxx        x    ",
   "    x          x            x                               x             x        x    ",
   "    x          x            x         xxxxxxxx              x!!!!!!!!     x        x    ",
   "    x          x            x      xxxx                     x!!!!!!xv     x      xxx    ",
   "    xx         x     xxxxxxxx         x                     =!!!!!!x      x        x    ",
   "    x                       x         x                     x!!!!!!x      x        x    ",
   "    x                       xxx       x     xxxxxxxxxxxxxxxxxxxxxxxx      xx       x    ",
   "    x                       x         x                                            x    ",
   "    xxxxxxxxxxxxxxxxxxxxxxxxx         x                                            x    ",
   "    x               x               xxx                                            x    ",
   "    x               x                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxx    ",
   "    x               x                 x!!!!!!!!!!!!!!!x              x             x    ",
   "    x               x       xxxxxxxxxxxvxxxxxxxxxxxvxxx              x             x    ",
   "    x                       x                         x      xxxxxxxxx             x    ",
   "    x                       x                         x     xx!!!!!!!xxxxxxx       x    ",
   "    x       xxxxxxxxxxxxxxxxx             xx          x      x!!!!!!!=             x    ",
   "    x                                     x           x      x!!!!!!!              x    ",
   "    x                                     x           xx     xxxxxxxxxxxxxxxxx     x    ",
   "    x                                     x     |     x                            x    ",
   "    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x                            x    ",
   "                                                x  o  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    ",
   "                                                xxxxxxx                                 ",
   "                                                                                        "],
  ["                                                                                                              ",
   "       x   x    xxx    x     x                   x           x  xxxxxxxxxxx   xx      x        xx             ",
   "       x   x   x   x   x     x                   x           x       x       x  x     x       xxxx            ",
   "       x   x  x     x  x     x                   x     x     x       x       x   x    x       xxxx            ",
   "        x x   x     x  x     x                   x     x     x       x       x    x   x      xxxxxx           ",
   "         x    x     x  x     x                   x     x     x       x       x     x  x       xxxx            ",
   "         x     x   x    x   x                     x   x x   x        x       x      x x       xxxx            ",
   "         x      xxx      xxx                       xxx   xxx    xxxxxxxxxxx  x       xx        xx             ",
   "                                                                                                              ",
   "                                                                                               xx             ",
   "     @                                                                                        xxxx            ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
